Using device: cuda
No checkpoint found at '/arc/home/Amirabezine/deepSpectra/checkpoints//checkpoint_latest.pth.tar'
No checkpoint found at '/arc/home/Amirabezine/deepSpectra/checkpoints//checkpoint_best.pth.tar'
  0%|          | 0/10 [00:00<?, ?it/s]/opt/conda/lib/python3.11/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
  0%|          | 0/10 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "/arc/home/Amirabezine/deepSpectra/./src/train.py", line 166, in <module>
    trained_generator, train_loss_history, val_loss_history = train_glo(generator, train_loader, val_loader, latent_dim, config, device)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/arc/home/Amirabezine/deepSpectra/./src/train.py", line 77, in train_glo
    loss = mse_loss(flux_hat, flux)
           ^^^^^^^^
NameError: name 'mse_loss' is not defined
